apiVersion: apps/v1
kind: Deployment
metadata:
  name:  aspnetapp-deployment
  namespace: default
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  replicas: 3
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      name: "aspnetapp-pod"
      labels:
        app: "aspnetapp"
    spec:
      containers:
        - name: aspnetapp-container
          image: "webappcontainer:v1"
          resources:
          env:
            - name: DB_CONNECTION
              value: "data source=mssql-service,1433; initial catalog=MyDb;persist security info=True;user id=sa;password=yourStrong(!)Password;TrustServerCertificate=True"
          ports:
            - containerPort: 80
---            
apiVersion: v1
kind: Service
metadata:
  name: "aspnetapp-service"
spec:
  selector:
    app: "aspnetapp"
  ports:
     - port: 8080
       nodePort: 30090
  type: NodePort