apiVersion: v1
kind: Pod
metadata:
  name: "mssql-pod"
  namespace: default
  labels:
    app: "mssql"
spec:
  containers:
    - name: mssql-container
      image: "mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04"
      resources:
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "yourStrong(!)Password"
      ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: "mssql-service"
spec:
  selector:
    app: "mssql"
  ports:
    - port: 1433
      nodePort: 31433
  type: NodePort
