// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore;

namespace CommonLibrary.Database;

public partial class OrderStateContext : SagaDbContext
{
    public OrderStateContext(DbContextOptions<OrderStateContext> options)
        : base(options)
    {
    }

    protected override IEnumerable<ISagaClassMap> Configurations
    {
        get
        {
            yield return new OrderStateMap();
        }
    }

    //public virtual DbSet<OrderState> OrderStates { get; set; }

    //protected override void OnModelCreating(ModelBuilder modelBuilder)
    //{
    //    modelBuilder.Entity<OrderState>(entity =>
    //    {
    //        entity.HasKey(e => e.CorrelationId).HasName("PK_OrderStateData");

    //        entity.ToTable("OrderState");

    //        entity.Property(e => e.CorrelationId).ValueGeneratedNever();
    //        entity.Property(e => e.OrderAcceptDateTime).HasColumnType("datetime");
    //        entity.Property(e => e.OrderCancelDateTime).HasColumnType("datetime");
    //        entity.Property(e => e.OrderCreationDateTime).HasColumnType("datetime");
    //        entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
    //    });

    //    OnModelCreatingPartial(modelBuilder);
    //}

    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}