apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: nginx:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
      ports:
        - containerPort: 80
          name: http
