apiVersion: v1
kind: Pod
metadata:
  name: mypod-nginx
  namespace: dev
  labels:
    name: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80