@AuthService_HostAddress = http://localhost:5284/api

POST {{AuthService_HostAddress}}/auth/login
Content-Type: application/json
Accept: application/json
{
    "email": "admin@gmail.com",
    "password": "Admin@12345678"
}
###

